# Boolean indexing(boolean is true or false)
ab indexing kay liyay true false say data aeyga numbers denaysay nahi

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
names == 'saad'

array([False, False, False, False, False, False, False])

In [4]:
data = np.random.randn(7,4)
data

array([[-1.00095393e+00,  2.41418752e-01,  7.19507991e-01,
        -4.00363498e-01],
       [-2.77696481e-01,  8.54462462e-01, -1.67858601e+00,
        -1.71209409e+00],
       [ 1.18960821e-01, -1.27610532e-01,  3.22787775e-01,
        -5.68709110e-01],
       [-1.14799302e+00, -2.37978038e-01,  1.12844185e+00,
         5.57975097e-01],
       [-1.68058236e+00, -1.08911681e+00, -1.25654527e+00,
         5.73662236e-01],
       [-9.96573362e-01,  1.08149579e-01,  2.83713773e+00,
        -1.70401029e-03],
       [-9.30913883e-01, -6.31172778e-02, -5.70983952e-01,
        -1.33273605e-01]])

In [5]:
data>1#it gives only the position

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [6]:
data[data>1]#syntax for exact value 

array([1.12844185, 2.83713773])

In [7]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names=='Bob']

array([[-1.00095393,  0.24141875,  0.71950799, -0.4003635 ],
       [-1.14799302, -0.23797804,  1.12844185,  0.5579751 ]])

In [9]:
data[True,False,False,False,False,True]#it gives an object
#so must give it boolean array

array([], shape=(0, 7, 4), dtype=float64)

In [10]:
data1 = np.random.randn(7,4)
data1

array([[-0.66509578,  0.94754606,  1.9245982 , -0.67822259],
       [-0.64949445, -0.23652801,  1.36725159,  0.63942975],
       [ 0.95180603, -0.92358844,  0.82996245,  0.03710665],
       [ 0.96135681, -0.84385447, -1.670631  ,  1.80458846],
       [ 1.56085804, -0.88834371, -0.02350891,  0.56733486],
       [ 1.17626621,  0.5509332 , -0.92819041,  1.6469756 ],
       [-1.51863901, -0.68727708, -0.29351248,  1.63084463]])

In [11]:
bol =np.array([True,False,False,False,False,True,False],dtype='bool')
data1[bol]

array([[-0.66509578,  0.94754606,  1.9245982 , -0.67822259],
       [ 1.17626621,  0.5509332 , -0.92819041,  1.6469756 ]])

In [12]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[names!='Bob']

array([[-2.77696481e-01,  8.54462462e-01, -1.67858601e+00,
        -1.71209409e+00],
       [ 1.18960821e-01, -1.27610532e-01,  3.22787775e-01,
        -5.68709110e-01],
       [-1.68058236e+00, -1.08911681e+00, -1.25654527e+00,
         5.73662236e-01],
       [-9.96573362e-01,  1.08149579e-01,  2.83713773e+00,
        -1.70401029e-03],
       [-9.30913883e-01, -6.31172778e-02, -5.70983952e-01,
        -1.33273605e-01]])

In [14]:
condition = names!='Bob'

In [17]:
data[condition]

array([[-2.77696481e-01,  8.54462462e-01, -1.67858601e+00,
        -1.71209409e+00],
       [ 1.18960821e-01, -1.27610532e-01,  3.22787775e-01,
        -5.68709110e-01],
       [-1.68058236e+00, -1.08911681e+00, -1.25654527e+00,
         5.73662236e-01],
       [-9.96573362e-01,  1.08149579e-01,  2.83713773e+00,
        -1.70401029e-03],
       [-9.30913883e-01, -6.31172778e-02, -5.70983952e-01,
        -1.33273605e-01]])

In [15]:
data[~condition]

array([[-1.00095393,  0.24141875,  0.71950799, -0.4003635 ],
       [-1.14799302, -0.23797804,  1.12844185,  0.5579751 ]])

In [16]:
data[~condition,1]

array([ 0.24141875, -0.23797804])

In [22]:
data[condition,1:3]

array([[ 0.85446246, -1.67858601],
       [-0.12761053,  0.32278777],
       [-1.08911681, -1.25654527],
       [ 0.10814958,  2.83713773],
       [-0.06311728, -0.57098395]])

In [20]:
data[condition,0:3]

array([[-0.27769648,  0.85446246, -1.67858601],
       [ 0.11896082, -0.12761053,  0.32278777],
       [-1.68058236, -1.08911681, -1.25654527],
       [-0.99657336,  0.10814958,  2.83713773],
       [-0.93091388, -0.06311728, -0.57098395]])

In [29]:
data2=np.arange(28).reshape(7,4)
print(data2)
print(condition)
data2[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [30]:
data3=np.arange(28).reshape(7,4)
print(data3)
print(~condition)
data3[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [32]:
data3=np.arange(28).reshape(7,4)#must negate in slicing
print(data3)
print(condition)
data3[~condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2],
       [13, 14]])

In [33]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [34]:
cond = (names=='Bob')& (names=='Joe')
cond

array([False, False, False, False, False, False, False])

In [35]:
Cond =(names=='Bob')|(names=='Joe')
Cond

array([ True,  True, False,  True, False,  True,  True])

In [39]:
arr3 = np.empty((8,4))
for i in range(8):
    arr3[i]=i
    print(arr3)


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [25]:
arr3 = np.empty((8,4))
for i in range(8):
    arr3[i]=i
arr3


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [23]:
arr4=np.empty((8,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
arr3[[1,2,3]]#still on first row

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [43]:
arr3[[4,0,2,3]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [26]:
arr3

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
arr3[[4,0,1,2],[2,3,0,1]]#give answer in 1d form
#draw an ordered matrix
#(4,2),(0,3),(1,0),(2,1)

array([4., 0., 1., 2.])

In [46]:
arr = np.arange(32).reshape(8,4)#: means all so it give answer in 2d form
print(arr)
arr[[1,5,7,2]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
#(1,0)(1,3)(1,1),(1,2),(5,0t)....

   

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [47]:
t = arr.T
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [ ]:
arr.transponse()

In [48]:
arr1d=np.array([1,3,5,6,7])


In [49]:
reminder,whole_part=np.modf(arr1d)

In [50]:
reminder

array([0., 0., 0., 0., 0.])

In [51]:
whole_part

array([1., 3., 5., 6., 7.])

In [52]:
#.any()agar ek bhi value true hogi to true return karta hae
#.all()agar ek bhi value false hogi to false return karta hae


In [53]:
a = [22,33,44,55,66,77,88,99]
st= set(a)

In [54]:
st

{22, 33, 44, 55, 66, 77, 88, 99}

In [55]:
#the samething do the unique function
aset={33,44,55,88,55,99,88}#remove similar elements
s=set(aset)
s

{33, 44, 55, 88, 99}

# Concatenation

In [29]:
arr1= np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2 = np.array([[8,9,10],[11,12,13]])
arr2

array([[ 8,  9, 10],
       [11, 12, 13]])

In [62]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [63]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [64]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [65]:
np.stack([arr1,arr2])#not a part but stack

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [67]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [68]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [69]:
np.stack([arr1,arr2],axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [70]:
np.stack([arr1,arr2],axis=1)

array([[[ 1,  2,  3],
        [ 8,  9, 10]],

       [[ 4,  5,  6],
        [11, 12, 13]]])

In [75]:
arr5=np.arange(36).reshape(6,6)
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
np.vsplit(arr5,3)#split row wise

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [77]:
np.hsplit(arr5,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [79]:
arr5.repeat(3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
       17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
       22, 23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28,
       28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33,
       34, 34, 34, 35, 35, 35])

In [80]:
np.tile(arr5,3)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,
         4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11,  6,  7,  8,  9,
        10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23, 18, 19, 20, 21,
        22, 23],
       [24, 25, 26, 27, 28, 29, 24, 25, 26, 27, 28, 29, 24, 25, 26, 27,
        28, 29],
       [30, 31, 32, 33, 34, 35, 30, 31, 32, 33, 34, 35, 30, 31, 32, 33,
        34, 35]])

In [31]:
np.column_stack([arr1,arr2])

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])