In [1]:
a =[1,2,3,4,5,6,7,8,9]

In [2]:
b =[]
for num in a:
    b.append(num*5)
b

[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])
a*5
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])
a*5


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
%time
b =[]
for num in a:
    b.append(num*5)
b

Wall time: 0 ns


[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [38]:
#%time yay bateay ga kay kitnay time may yay vector multiply hoga
#5 say iss ka time for loop say kaam hoga. 

In [9]:
 %time
a = np.array([1,2,3,4,5,6,7,8,9])
a*5


Wall time: 0 ns


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
numpyarray =np.array([22,44,55,66])
print(numpyarray)
type(numpyarray)

[22 44 55 66]


numpy.ndarray

In [15]:
numpyarray =np.array([22,44.5,55,66])
print(type(numpyarray))
(numpyarray)

<class 'numpy.ndarray'>


array([22. , 44.5, 55. , 66. ])

In [17]:
numpyarray =np.array([22,44.5,55,66],dtype='float32')
print(type(numpyarray))
numpyarray

<class 'numpy.ndarray'>


array([22. , 44.5, 55. , 66. ], dtype=float32)

In [9]:
numpyarray =np.array([22,44.5,55,66],dtype='int32')
print(type(numpyarray))
print(numpyarray.dtype)
numpyarray

<class 'numpy.ndarray'>
int32


array([22, 44, 55, 66])

In [19]:
numpyarray =np.array([22,44.5,55,66],dtype='int8')
print(type(numpyarray))
numpyarray

<class 'numpy.ndarray'>


array([22, 44, 55, 66], dtype=int8)

In [22]:
numpyarray =np.array([22000,44.5,55987,999066],dtype='int8')
print(type(numpyarray))
numpyarray

<class 'numpy.ndarray'>


array([ -16,   44,  -77, -102], dtype=int8)

In [8]:
randomArray = np.random.randn(10)*100#randn=distributed number in normal form

In [9]:
randomArray

array([ -10.05518141, -177.52952448,  -49.9886713 ,   94.80752277,
        164.41268064,  -47.13077235,  -43.91329875,  -69.65666977,
        -35.02914968,  -62.30181681])

# dimension decide the axis of object
1.axis is the part of dimension

In [27]:
randomArray.ndim

1

In [28]:
randomArray.shape

(10,)

## array>>>> vector
matrix>>>> tensor

In [29]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [30]:
twoD.shape

(4, 3)

In [31]:
miscD = np.array([[99]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [32]:
miscD = np.array([[[99]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [33]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [1]:
import numpy as np

In [35]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=np.random.rand(12)
b

array([0.47067621, 0.34425046, 0.35301546, 0.74894419, 0.71101915,
       0.22801841, 0.13205608, 0.33215726, 0.68613936, 0.88954046,
       0.29980268, 0.93925452])

In [15]:
np.random.seed(5)



In [16]:
c=np.random.rand(3)
c

array([0.22199317, 0.87073231, 0.20671916])

In [12]:
a=np.random.RandomState(12345)
a

In [22]:
a =np.arange(24).reshape(2,3,4)#resahpe may wo numbers aengay jin ka product 12 ho
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
 #np.ravel(a)
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
b =np.arange(12).reshape(3,4)#resahpe may wo numbers aengay jin ka product 12 ho
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
fat = flat.reshape(3,4,2)#flat one dimension may lay jaey ga
fat

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [46]:
h = np.array(56)
print(h.ndim)

0


In [2]:
import numpy as np

In [3]:
twoD = np.arange(36).reshape(6,6)
twoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
np.dot(twoD,twoD)

array([[ 330,  345,  360,  375,  390,  405],
       [ 870,  921,  972, 1023, 1074, 1125],
       [1410, 1497, 1584, 1671, 1758, 1845],
       [1950, 2073, 2196, 2319, 2442, 2565],
       [2490, 2649, 2808, 2967, 3126, 3285],
       [3030, 3225, 3420, 3615, 3810, 4005]])

In [8]:
f=threeD.reshape(36)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [4]:
threeD = twoD.reshape(3,3,4)
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [31]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [32]:
np.dot(a,a)

14

In [9]:
np.dot(f,f)

14910

In [51]:
reback = threeD.reshape(6,6)
reback

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [52]:
threeD = np.array([[[1,2,3],[4,5,6],[5,6,7]],[[1,3,4],[1,2,3],[6,8,9]],[[9,0,8],[5,8,7],[9,0,6]]])
threeD                

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]],

       [[1, 3, 4],
        [1, 2, 3],
        [6, 8, 9]],

       [[9, 0, 8],
        [5, 8, 7],
        [9, 0, 6]]])

In [53]:
#two will be add if their shape is same

In [54]:
twoD+twoD#mirror addition or element wise operation

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [55]:
twoD-twoD#mirror subtraction or element wise operation

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [56]:
twoD/twoD#mirror division or element wise operation

C:\Users\me\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [57]:
twoD*twoD#mirror mutiplication or element wise operation

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [58]:
m1 = np.arange(12).reshape(4,3)

In [63]:
m2 = np.random.randn(12).reshape(4,3)

In [64]:
m1+m2

array([[1.52596356, 1.10047367, 1.19110677],
       [4.05479962, 3.7276905 , 5.10565442],
       [6.56926469, 6.50514936, 7.65395597],
       [9.45274513, 9.80129606, 9.89198032]])

In [65]:
m9 = np.arange(12).reshape(4,3)

In [68]:
m6 = np.random.randn(16).reshape(4,4)

In [69]:
m6+m9

ValueError: operands could not be broadcast together with shapes (4,4) (4,3) 

In [71]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

# Method one for multiplication of matrix like linear algebra

In [72]:
m1@m3#@ multiply the matrix in the manner of linear algebra but 
#no of column(matrix 1) and no of rows(matrix 2) are equal

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

#  Method two for multiplication of matrix like linear algebra

In [74]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

# Method three for multiplication of matrix like linear algebra

In [75]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [76]:
m = np.array([[[1,2],[3,2],[]])
m

array([[1, 2],
       [3, 2]])

In [78]:
zeeros = np.zeros(4)
zeeros

array([0., 0., 0., 0.])

In [79]:
zeeros = np.zeros(4,dtype ='int8')
zeeros

array([0, 0, 0, 0], dtype=int8)

In [34]:
zeeros = np.zeros((4,5),dtype = 'int32')
zeeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [82]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
ones = np.ones((5,5))
ones*50

array([[50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.]])

In [85]:
fullll = np.full((4,4),100)#multiply all elements of a matrix by hundred
fullll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [87]:
emptyyy= np.empty((4,4,4))#show 0 value if no garbbage were present in ram 
#garbage value = which refrence is remove but value exist in a memory
#dont use it for 0 because sometimes it return garbage value
emptyyy

array([[[4.45e-323, 0.00e+000, 1.35e-321, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]]])

In [89]:
like = np.zeros_like(m3)#it can copy the shape of m3 and return zero
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [90]:
np.eye(3,3)#eye use for identity marix
#identity matrix:
#*whose daigonal is 1
#*whose determinant s  0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
i =np.eye(5,5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
s=np.array(i,dtype="int")
s

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [95]:
j =i.astype("int")
j

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Basic Indexing and Sliciing
# main difference is type

In [96]:
alist = [99,77,55,33,11]
print(alist[0])
type(alist[0])

99


int

In [41]:
alist = [99,77,55,33,11]
a=alist[0:3]
print(a)
type(a)

[99, 77, 55]


list

In [45]:
alist[0:3]=[42,42,42]

In [46]:
alist

[42, 42, 42, 33, 11]

In [99]:
tDarray = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [104]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])

In [100]:
tDarray[3,2]

20

In [101]:
tDarray[3][2]

20

In [102]:
#tDarray[row,coloumn]
#tDarray[start:end,start:end]
tDarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [103]:
tDarray[5:,3:4]

array([[33]])

In [3]:
arr1d =np.array([44,55,66,77])
arr1d

array([44, 55, 66, 77])

In [4]:
arr1d[1]

55

In [6]:
arr1d[1:2]

array([55])

In [7]:
arr1d[-1:-3]

array([], dtype=int32)

In [8]:
arr2d = np.array([[1,2,3],[3,4,5],[4,5,6]])
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [9]:
arr2d[:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
arr2d[:2,1:]

array([[2, 3],
       [4, 5]])

In [11]:
arr2d[:2,1:2]

array([[2],
       [4]])

In [12]:
arr2d[1][2]#indexing first method

5

In [13]:
arr2d[1,2]#indexing second method

5

In [50]:
arr3d = np.array([[[1,2,4],[200,300,500],[390,490,120]],[[2,4,6],[3,5,7],[1,2,3]]])
arr3d
arr3d.shape

(2, 3, 3)

In [15]:
arr3d.ndim

3

In [16]:
arr3d.shape#1=2d,3=rows,3=columns

(1, 3, 3)

In [17]:
arr3d[0][2]

array([390, 490, 120])

In [19]:
arr3d[0][2][1]#0=2d,2=rows,2=columns

490

In [21]:
arr3d[1][0]#in 2d 1 index is not present

IndexError: index 1 is out of bounds for axis 0 with size 1

In [51]:
arrsec3d= np.array([[[1,2,3],[3,4,5],[6,7,8]],
                        [[22,23,24],[23,45,67],[12,34,56]]])
arrsec3d

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[22, 23, 24],
        [23, 45, 67],
        [12, 34, 56]]])

In [52]:
arr3d[0][0][0]

1

In [26]:
arrsec3d[0,:2,1:]

array([[2, 3],
       [4, 5]])

In [54]:
arr=np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5]
             ,[8,2,4,9,7]])
arr

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [56]:
arr[[2,3],[2,4]]

array([6, 3])

In [58]:
arr2 = np.arange(1,37).reshape(6,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [63]:
#arr2[row,column]
arr2[2:3,0:6]

array([[13, 14, 15, 16, 17, 18]])

In [64]:
#[:]its means all
#[] its also means all
arr2[2]#in slicing of row all column slice writting is not necessary

array([13, 14, 15, 16, 17, 18])

In [65]:
arr2[,2]

SyntaxError: invalid syntax (<ipython-input-65-048a6e59a98f>, line 1)

In [66]:
arr2[:,2]#for column firstly define all row

array([ 3,  9, 15, 21, 27, 33])

In [67]:
arr2[1:5]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [68]:
arr2[2:4,5]

array([18, 24])

In [70]:
arr2[2:4,-1]#it answer in vector form

array([18, 24])

In [71]:
arr2[2:4,5:]#it answer in 2d array

array([[18],
       [24]])

In [62]:
arr2[:,-2:-1]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [74]:
arr2[:,:-2]#steps in column

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28],
       [31, 32, 33, 34]])

In [75]:
arr2[:,::2]#:2 is ue for steps

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [77]:
arr2[:,::-2]#:-2 is use for steps but in reverse
#steps in column

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [78]:
arr2[::2,::2]#steps in row

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [79]:
arr2[0:5:2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])